config/routes.rb
Rails.application.routes.draw do

  root "users#index"
  resources :events
  resources :users
  resources :sessions

  # get 'sessions/new'
  # post "sessions" => "session#create"

  # get "users/:id" => "users#show"

end

app/models/user.rb
class User < ActiveRecord::Base

    has_many :attendees
    has_many :events, through: :attendees

	EMAIL_REGEX = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]+)\z/i
    
        validates :first_name, presence: true,
                                length: {within: 2..50}
    
        validates :last_name, presence: true,
                                length: {within: 2..50}
        
        validates :email, presence: true,
                            format: {with: EMAIL_REGEX, message: "incorrect email format"},
                            uniqueness: {case_sensitive: false}
        
        validates :password, presence: true,
                                length: {within: 6..20}
    
        before_save {self.email = email.downcase}
        has_secure_password
 

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  	@users = User.all
  end

  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
      sign_in @user
  		redirect_to users_path, notice: "User was successfully created."
  	else
  		flash[:errors_register] = @user.errors.full_messages
      	redirect_to :back
  	end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
  end

  private
  	def user_params
  		params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<div class="container">
	<h1>All Users</h1>
	<p class='success'><%= notice %></p>
	<% if signed_in? %>
		<p class='success'>Welcome, <%= current_user.first_name %>!</p>
		<p><%= link_to 'Logout', session_path(current_user), method: :delete, class: 'btn btn-primary' %></p>
	<% end %>
	<table>
		<thead>
			<tr>
				<th>First Name</th>
				<th>Last Name</th>
				<th>Email Address</th>
			</tr>
		</thead>
		<tbody>
			<% @users.each do |user| %>
				<tr>
					<td><%= user.first_name %></td>
					<td><%= user.last_name %></td>
					<td><%= user.email %></td>
				</tr>
			<% end %>	
		</tbody>
	</table>

	<% if !signed_in? %>
		<p><%= link_to 'Register', new_user_path, class: 'btn btn-primary' %></p>
		<p><%= link_to 'Login', new_session_path, class: 'btn btn-primary' %></p>
	<% end %>
</div>

app/views/users/new.html.erb
<div class="container">
	<h1>New User Registration</h1>
		<% if flash[:errors_register] %>
			<p>Please correct the following errors:</p>
			<% flash[:errors_register].each do |error| %>
				<p class='error'><%= error %></p>
			<% end %>
		<% end %>
	<%= simple_form_for @user do |f| %>
		<%=f.input :first_name %>
		<%=f.input :last_name %>
		<%=f.input :email %>
        <%=f.input :location%>
        <%= select_tag :state, options_for_select(us_states) %>
		<%=f.input :password %>
		<%=f.input :password_confirmation %>
		<%=f.button :submit, 'Register', class: 'btn btn-primary' %>
	<% end %>

	<p class='link'><%= link_to 'View All Users', users_path %></p>

</div>

app/views/users/newindex.html.erb
<h1>Welcome!</h1>

<div id="container">
	<form action='/users/create' method='post'>
    	<input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">
      <h3>Register</h3>
    	<div>
    		<label>First Name:</label>
	    	<input type='text' name='create[first_name]'>
    	</div>
      <div>
    		<label>Last Name:</label>
	    	<input type='text' name='create[last_name]'>
    	</div>
	    <div>
      <div>
    		<label>Email:</label>
	    	<input type='text' name='create[email]'>
    	</div>
      <div>
    		<label>Location:</label>
	    	<input type='text' name='create[location]'>
    	</div>
	    	<label>State:</label>
		    <select name="create[state]" class="select">
				<option value="WA">WA</option>
				<option value="CA">CA</option>
				<option value="AZ">AZ</option>
				<option value="NY">NY</option>
        <option value="IL">IL</option>
				<option value="OH">OH</option>
			</select>
	    </div>
      <div>
    		<label>Password:</label>
	    	<input type="password" name='create[password_digest]'>
    	</div>
      <p>*Password should be at least 8 characters
      <%# <div>
    		<label>Confirm PW:</label>
	    	<input type='text' name='create[location]'>
    	</div> %>
		<div>
			<input type='submit' value='Register'>
		</div>
    </form>
</div>

<body>
<% if flash[:errors] %>
  <% flash[:errors].each do |e| %>
    <%= e %>
  <% end %>
<% end %>
<% if current_user %>
  <form action="/sessions/<%=current_user.id%>" method="post">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <input type="hidden" name="_method" value="delete">
    <input type="submit" value="Log Out">
  </form>
<% end %> 
<%= yield %>

<div id="container2">
<h1>Please log in</h1>
<form action="/sessions" method="post">
  <input type="hidden" name:"authenticity_token" value"<%= form_authenticity_token %>">
    <p>
        <label>Email field</label>
        <input type="text" name="email">
    </p>
    <p>
        <label>Password field</label>
        <input type="text" name="password">
    </p>
    <input type="submit" value="Login">
</form>
</div>
</body>

app/views/users/oldIndex.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Location</th>
      <th>State</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.email %></td>
        <td><%= user.location %></td>
        <td><%= user.state %></td>
        <td><%= user.password %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Location:</strong>
  <%= @user.location %>
</p>

<p>
  <strong>State:</strong>
  <%= @user.state %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>